language: node_js
branches:
  only:
    - master
node_js:
  - "4.2"
  - "4.1"
  - "4.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  email:
    - phillip@flitbit.com